party/urls.py
from django.urls import path
from . import views

app_name = 'party'

urlpatterns = [
          path('', views.home, name='home'), 
          path('apply/',views.apply, name='apply')
]

party_website/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('party.urls')),
    re_path(r'^select2/', include('django_select2.urls')),
]

party/models.py
from django.db import models

# Create your models here.
class State(models.Model):
    """
        Model for states in India.
    """
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class District(models.Model):
    """
        Model for districts in various states.
    """
    name = models.CharField(max_length=200)
    parent_state = models.ForeignKey('State', on_delete=models.CASCADE, related_name='districts')

    def __str__(self):
        return self.name

class Member(models.Model):
    """
        Model to store data of members of  party
    """
    name = models.CharField(max_length=200)
    dob  = models.DateField(blank=True,null=True)
    gender = models.CharField(max_length=1,default='M')
    email = models.EmailField(blank=True)
    phone = models.CharField(max_length=10)
    state = models.CharField(max_length=50)
    district = models.CharField(max_length=50,)
    address = models.CharField(max_length=200,blank=True)
    pincode = models.CharField(max_length=6,blank=True)
    voterID = models.CharField(max_length=10,blank=True)

    def __str__(self):
        return self.name + '(' + self.district + ')'

party/forms.py
import datetime

from django import forms
from django.core.validators import EmailValidator, RegexValidator
from django.forms import CharField
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from .models import State, District
from django_select2.forms import ModelSelect2Widget

def validate_date(date):
    """
        Date validation for DOB and age above 18 years
    """
    if datetime.date.today() < date:
        raise ValidationError(_('Date of birth can\'t be a future date'))
    if datetime.date.today().year - date.year < 17:
        raise ValidationError(_('You must be atleast 18 years old.')) 
class MemberRegistrationForm(forms.Form):
    """
        Form for registration of members.
    """
    name = forms.CharField(label='Name',
                           validators=[
                               RegexValidator(
                                        regex=r'([A-Za-z]|\s)+',
                                        message='Invalid Characters in name',
                                        )
                                 ],
                           )

    dob = forms.DateField(
                            label = 'Date Of Birth', 
                            required = False, 
                            validators=[validate_date],
                            widget=forms.widgets.DateInput(attrs={'type': 'date'})
                                
                        )
    
    gender = forms.ChoiceField(
                                label='Gender', 
                                choices=(
                                    ('M', 'Male'),
                                    ('F', 'Female'),
                                    ('O', 'Other'),
                                )
    )

    email = forms.EmailField(
                                label='Email', 
                                required = False,
                            )
    phone_number = forms.CharField(
                                    label='Phone No.', 
                                    validators=[
                                            RegexValidator(regex=r'\d{10}',
                                            message='Enter your 10 digit mobile number.'
                                            )
                                        ],
                                   )
                            
    state = forms.ModelChoiceField(
                                label = 'State',
                                queryset=State.objects.all(),
                                widget=ModelSelect2Widget(
                                    model = State,
                                    search_fields = ['name_icontains'],
                                    dependent_fields={'district': 'districts'},

                                ),
                            )
    district = forms.ModelChoiceField(
                                        label = 'District',
                                        queryset = District.objects.all(),
                                        widget = ModelSelect2Widget(
                                            model = District,
                                            search_fields = ['name_icontains'],
                                            dependent_fields = {'state':'parent_state'},
                                            max_results = 500,
                                        )
                )
    address = forms.CharField(
                label = 'Address',
                required = False,
                max_length = 200,
                widget=forms.Textarea,
            )
    pin_code = forms.CharField(
                    label = 'Pin Code',
                    required = False,
                    validators=[
                        RegexValidator(
                            regex=r'\d{6}',
                            message = 'Enter a valid pin code',
                        )
                    ]
                )
    voterId = forms.CharField(
                    label = 'Voter ID',
                    required = False,
                    validators=[
                                RegexValidator(
                                                regex=r'[A-Z]{3}\d{7}',
                                                message='Enter valid VOTER ID number.',
                                        )
                                ],
                )
    disclaimer = '''I am above 18 years , and not enrolled as a government employee.
                    I am not a member of any other political party registered with the Election Commission of India.
                    I am not a member with any organization whose views, policies or actions are in 
                    conflict with the objective of the party. I have not been convicted of any offense 
                    involving moral turpitude. I hereby consent to receiving any communication from the party either in writing, 
                    electronically and/or in any audio-visual format via phone (including SMS/MMS), email and/or at my address.'''
    Iagree = forms.BooleanField(
                label= disclaimer,
            )

party/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .forms import MemberRegistrationForm
from .models import Member, State, District

app_name = 'party'

def home(request):
    return render(request,'party/base.html',{})

def apply(request):
    if request.method == 'GET':
        form = MemberRegistrationForm()
        context = {
            'form':form,
        }
        return render(request,'party/apply.html',context)
    else:
        form = MemberRegistrationForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            data = form.cleaned_data
            member = Member(
                            name=data['name'], 
                            dob=data['dob'], 
                            gender=data['gender'],
                            email=data['email'],
                            phone=data['phone_number'],
                            state=data['state'].name,
                            district=data['district'].name,
                            address=data['address'],
                            pincode = data['pin_code'],
                            voterID = data['voterId'],
                        )
            member.save()
            context = {
                'form':form,
                'message':'Thank you for joining us and becoming part of our movement.'
            }
            return render(request,'party/apply.html',context)
        return render(request,'party/apply.html',{'form':form})

party/templates/party/apply.html
{% extends 'party/base.html' %}
{% block content %}
    {% if message %}
    <div class="apply-message">
        {{message}}
    </div>
    {% endif %}
<form action="." method="POST" class="apply-form">
    {% csrf_token %}
    {{ form.as_p }}
<input type="submit" name="Register" value="Register" class="apply-submit">
</form>
{% endblock %}

party/templates/party/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <title>Rashtriya Bandhuthva Party</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'base.css'%} ">
  <link rel="stylesheet" href="{% static 'apply.css'%} ">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  {{form.media}}
  {{ form.media.css }}
</head>
<body>

    <nav class="navbar navbar-default fixed-top">
        <div class="container-fluid">
            <img src="{%static 'cooker.jpg'%}" style="width:40px;height:40px;float: left;margin-right: 5%">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Rashtriya Bandhuthva Party</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">About</a></li>
                <li><a href="#">Elections</a></li>
                <li><a href="#">Media</a></li>
                <li><a href="{% url 'party:apply' %}"><button>Apply</button></a></li>
            </ul>
        </div>
    </nav>
    <div class="content-except-nav-foot">
        <div class="news-ticker">
            <div class="news-ticker-heading">Updates</div><div class="news-ticker-txt" ><marquee>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</marquee></div>
        </div>
        {% block content %}
        {% endblock %}
    </div>
    <footer>
        <div id="footer_cols">
        <div class="footer_col1">
            <h1>
                CONTACT US
            </h1>
            <p>Party Cordinator<br>
                Mr. Amul Palekar
            </p>
            <p>+91XXXXXXXX</p>
        </div>
        <div class="footer_col2">
            <div>
                <a href="#">HOME</a>
            </div>
            <div>
                <a href="#">MEDIA</a>
            </div>
            <div>
                <a href="#">ABOUT US</a>
            </div>
            <div>
                <a href="#">SIGN UP!</a>
            </div>
        </div>
        </div>
        <!-- social media hover effect  -->
        <div id="footer_social_media_buttons">
            <ul>
                <li>
                    <ahref="#">
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>
                        <span class="fa fa-facebook" aria-hidden="true"></span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>
                        <span class="fa fa-instagram" aria-hidden="true"></span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>
                        <span class="fa fa-google-plus" aria-hidden="true"></span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>
                        <span class="fa fa-linkedin" aria-hidden="true"></span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>
                        <span class="fa fa-twitter" aria-hidden="true"></span>
                    </a>
                </li>
            </ul>
        </div>
    </footer>
    {{ form.media.js }}
</body>
</html>